image: alpine:latest
before_script:
  - apk --update add lftp

stages:
  - deploy
  
job:deploy:
  stage: deploy
  script:
  - lftp -e "set ssl:verify-certificate no; open $FTP_HOST; user $FTP_USERNAME $FTP_PASSWORD; mirror -X .* -X .*/ --reverse --verbose --delete . $FTP_PATH; bye"

  only:
  - master
